name: Deploy to Bluehost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to Bluehost
        uses: easingthemes/ssh-deploy@v2.2.7
        with:
          server: your-bluehost-domain.com
          username: bluehost-username
          password: ${{ secrets.BLUEHOST_PASSWORD }}
          local_path: ./build
          remote_path: public_html 